### PR TITLE
Only discard shift key in mac OS

### PR DESCRIPTION
**Pull request by jamieabc**
Ignore 'shift' key event only in MAC OS

### CODE REVIEW

**Comment by ycavatars** [comment]
@Xuhao Please review Aaron's PR. If we don't enable the shift key, we can't scroll horizontally neither with Mac's trackpad nor usb mouse.

**Comment by Xuhao** [comment]
Can you apply the modification in `lib/index.jsx` and dist as well?

**Comment by ycavatars** [comment]
Do you mean execute `npm run lib` and `npm run dist`?

**Comment by Xuhao** [comment]
@ycavatars Yes, dist version for browser use

**Pull request merged**
